#!/usr/bin/env swift

/*
 Export All Thai Words from Core Data

 Dette scriptet eksporterer ALLE Thai-ord fra din Core Data-database
 til en JSON-fil som kan brukes av PyThaiNLP-generatoren.

 Bruk:
     swift export_all_words.swift

 Output:
     all_thai_words.json - Klar for PyThaiNLP-prosessering
*/

import Foundation
import CoreData

// MARK: - Core Data Stack Setup

let storeURL = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
    .appendingPathComponent("gNorsk")
    .appendingPathComponent("gNorsk.sqlite")

print("📂 Søker etter Core Data database:")
print("   \(storeURL.path)")

guard FileManager.default.fileExists(atPath: storeURL.path) else {
    print("❌ Finner ikke Core Data database!")
    print("   Sørg for at appen har kjørt minst en gang.")
    print("\n💡 Alternativ: Bruk exportAllWords() funksjonen i appen")
    exit(1)
}

// Load model
let modelURL = URL(fileURLWithPath: "/Users/geirlapstuen/Swift/gNorsk/CoreData/gNorsk.xcdatamodeld")
guard let model = NSManagedObjectModel(contentsOf: modelURL) else {
    print("❌ Kunne ikke laste Core Data-modell")
    exit(1)
}

// Create persistent store coordinator
let coordinator = NSPersistentStoreCoordinator(managedObjectModel: model)

do {
    try coordinator.addPersistentStore(
        ofType: NSSQLiteStoreType,
        configurationName: nil,
        at: storeURL,
        options: [
            NSReadOnlyPersistentStoreOption: true,
            NSMigratePersistentStoresAutomaticallyOption: true,
            NSInferMappingModelAutomaticallyOption: true
        ]
    )
} catch {
    print("❌ Kunne ikke åpne database: \(error)")
    exit(1)
}

// Create context
let context = NSManagedObjectContext(concurrencyType: .mainQueueConcurrencyType)
context.persistentStoreCoordinator = coordinator

// MARK: - Fetch All Words

print("\n🔍 Henter alle Thai-ord fra databasen...")

let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "ThaiWords")
fetchRequest.sortDescriptors = [NSSortDescriptor(key: "thai", ascending: true)]

do {
    let results = try context.fetch(fetchRequest) as! [NSManagedObject]

    print("✅ Funnet \(results.count) ord i databasen")

    // Extract unique Thai words
    var uniqueWords = Set<String>()

    for object in results {
        if let thaiWord = object.value(forKey: "thai") as? String,
           !thaiWord.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            uniqueWords.insert(thaiWord)
        }
    }

    print("📊 Unike ord: \(uniqueWords.count)")

    // Convert to JSON format for PyThaiNLP
    let jsonArray = uniqueWords.sorted().map { word in
        return [
            "text": word,
            "ipa": "",  // Will be generated by PyThaiNLP
            "syllables": []  // Will be generated by PyThaiNLP
        ]
    }

    // Write to file
    let outputURL = URL(fileURLWithPath: "/Users/geirlapstuen/Swift/gNorsk/Resources/all_thai_words.json")
    let jsonData = try JSONSerialization.data(withJSONObject: jsonArray, options: [.prettyPrinted, .sortedKeys])
    try jsonData.write(to: outputURL)

    print("\n✅ Eksportert til: \(outputURL.path)")
    print("\nNeste steg:")
    print("1. cd /Users/geirlapstuen/Swift/gNorsk/Scripts")
    print("2. python3 generate_thai_data.py --input ../Resources/all_thai_words.json")

} catch {
    print("❌ Feil ved henting av data: \(error)")
    exit(1)
}
